version: "3.7"
services:
  fastapi_app:
    init: true
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    environment:
      - PORT_APP=3003
    ports:
      - "127.0.0.1:3003:3003"
    depends_on:
      - slow_api

  slow_api:
    init: true
    build: ./slow_api
    expose:
      - "8051"